[tool.poetry]
name = "fibonacci"
version = "0.1.0"
description = ""
authors = ["Rob Bailiff"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
maturin = "^1.8.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
